---
- name: Download WAMPServer
  win_get_url:
    url: "{{wampserver}}"
    dest: C:\temp\wampserver.exe

- name: Create websoft9 directory
  win_file:
    path: C:\websoft9\wampserver
    state: directory

## 失败代码 /VERYSILENT无法识别？
# - name: Install WAMPServer
#   win_package:
#     path: C:\temp\wampserver.exe
#     product_id: wampserver
#     arguments:
#     - /VERYSILENT
#     - /DIR="C:\websoft9\wampserver"
#     state: present

- name: Install WAMPServer
  win_shell: C:\temp\wampserver.exe /VERYSILENT /DIR="C:\websoft9\wampserver"

- name: start apache & mysql
  win_service:
    name: "{{item}}"
    start_mode: auto
    state: started
  with_items:
    - wampapache64
    - wampmariadb64
    - wampmysqld64

- name: add mysql path environment variables
  win_path:
    elements:
      - 'C:\websoft9\wampserver\bin\apache\apache"{{apache_ver}}"\bin'
      - 'C:\websoft9\wampserver\bin\mysql\mysql"{{mysql_ver}}"\bin'
      - 'C:\websoft9\wampserver\bin\mariadb\mariadb"{{mariadb_ver}}"\bin'

- name: Reboot Machine
  win_reboot:
    reboot_timeout: 120
    connect_timeout: 15

## 重置MySQL&MariaDB密码
- name: Reset MySQL password
  win_command:
    mysqladmin -uroot password "{{mysql_password}}"
  args:
    chdir: C:\websoft9\wampserver\bin\mysql\mysql{{mysql_ver}}\bin

- name: Reset MariaDB password
  win_command:
    mysqladmin -uroot password "{{mariadb_password}}"
  args:
    chdir: C:\websoft9\wampserver\bin\mariadb\mariadb{{mariadb_ver}}\bin

- name: Create Credentials Directory
  win_file:
    path: C:\Credentials\
    state: directory

- name: Copy password.txt to Credentials
  win_template:
    src: password.txt.j2
    dest: C:\Credentials\password.txt

## 修改apache配置文件
- name: change httpd-vhsot.conf file
  win_template:
    src: templates/httpd-vhosts.conf.j2
    dest: C:\websoft9\wampserver\bin\apache\apache2.4.39\conf\extra\httpd-vhosts.conf

- name: Add 9panel configration file
  win_template:
    src: templates/9panel.conf.j2
    dest: C:\websoft9\wampserver\alias\9panel.conf

#　Restart Service
- name: Restart apache & mysql & mariadb
  win_service:
    name: "{{item}}"
    state: restarted
  with_items:
    - wampapache64
    - wampmariadb64
    - wampmysqld64

# 修改快捷方式
- name: delete default icon
  win_shortcut:
    dest: C:\Users\hl\Desktop\Wampserver64.lnk
    state: absent

- name: Create shotcut in public desktop
  win_shortcut:
    src: C:\websoft9\wampserver\wampmanager.exe
    dest: C:\Users\Public\Desktop\Wampserver64.lnk
    directory: C:\wamp64\

# 添加快捷方式到启动菜单
- name: Create shotcut in public desktop
  win_shortcut:
    src: C:\wamp64\wampmanager.exe
    dest: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\Wampserver64.lnk
    directory: C:\wamp64\
