- name: Create tampority directory
  win_file:
    path: C:\temp
    state: directory

- name: Download latest versiong phpmyadmin
  win_get_url:
    url: "{{phpmyadmin_url}}"
    dest: C:\temp\phpMyAdmin.zip

- name: Delete default phpmyadmin
  win_file:
    path: C:\websoft9\wampserver\apps\phpmyadmin{{old_phpmyadmin_version}}
    state: absent

- name: Unzip phpmyadmin
  win_unzip:
    src: C:\temp\phpMyAdmin.zip
    dest: C:\websoft9\wampserver\apps

- name: Rename phpmyadmin
  win_shell:
    ren C:\websoft9\wampserver\apps\phpMyAdmin-{{new_phpmyadmin_version}}-all-languages phpmyadmin

- name: copy phpmyadmin configuration file
  win_template:
    src: config.inc.php.j2
    dest: C:\websoft9\wampserver\apps\phpmyadmin\config.inc.php

- name: Replace phpmyadmin.conf
  win_template:
    src: phpmyadmin.conf.j2
    dest: C:\websoft9\wampserver\alias\phpmyadmin.conf

- name: Restart apache
  win_service:
    name: wampapache64
    state: restarted