# # 9panel
# - name: delete default source code
#   win_file:
#     path: C:\wamp64\www
#     state: absent

# - name: create www folder
#   win_file:
#     path: "{{item}}"
#     state: directory
#   with_items:
#     - C:\wamp64\www
#     - C:\wamp64\apps\9panel

# - name: Download 9panel
#   win_get_url:
#     url: https://github.com/Websoft9/9panel/archive/master.zip
#     dest: C:\temp\9panel.zip

# - name: unzip 9panel
#   win_unzip:
#     src: C:\temp\9panel.zip
#     dest: C:\temp\
#     delete_archive: yes

# - name: copy 9panel to \wamp64\apps\
#   win_copy:
#     src: C:\temp\9panel-master\
#     dest: C:\wamp64\apps\9panel
#     remote_src: yes

# - name: modify 9panel
#   win_lineinfile:
#     path: C:\wamp64\apps\9panel\js\websoft9.js
#     regexp: 'var set_infrastructure="LAMP";'
#     line: 'var set_infrastructure="WAMPServer";'

- name: copy 9panel to \wamp64\www\
  win_copy:
    src: C:\wamp64\apps\9panel\
    dest: C:\wamp64\www\
    remote_src: yes

- name: delete extra file
  win_file:
    path: C:\wamp64\www\{{item}}
    state: absent
  with_items:
    - index.html
    - db.html
    - ftp.html
    - tools.html

- name: Rename example.html
  win_shell: ren C:\wamp64\www\example.html index.html

- name: delete temporary directory
  win_file:
    path: C:\temp\
    state: absent