---
# 安装
- name: Create {{sqlserver_name}} directory 
  win_file:
    path: C:\temp\{{sqlserver_name}}
    state: directory

- name: Extract {{sqlserver_name}}
  win_shell: .\{{sqlserver_name}}.exe /u /x:C:\temp\{{sqlserver_name}}
  args:
    chdir: C:\temp\

- name: Copy ConfigurationFile.ini
  win_template:
    src: ConfigurationFile_2012.ini.j2
    dest: C:\temp\{{sqlserver_name}}\ConfigurationFile.ini

- name: Install SQLServer2012SP4
  win_shell:
    .\SETUP.EXE /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /CONFIGURATIONFILE=ConfigurationFile.ini
  args:
    chdir: C:\temp\{{sqlserver_name}}

- name: remove temp directory
  win_file:
    path: C:\temp\{{sqlserver_name}}
    state: absent

## 快捷方式
- name: Create SSMS lnk
  win_shortcut:
    src: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Ssms.exe
    dest: C:\Users\Public\Desktop\SQL Server 2012 Management Studio.lnk
    icon: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.ico